insert into products (name, category, description, url, price) values ('Morula Surprise', 'Alcoholic', 'Introducing "Morula Surprise" – a captivating blend crafted by Ibrew, encapsulating the essence
                        of Botswana''s cherished Morula fruit. Handpicked at peak ripeness, the Morula pulp forms the
                        heart of this exquisite beverage, infusing it with the authentic flavors of the African
                        savannah. Yet, it''s the unexpected twist that sets Morula Surprise apart – a harmonious fusion
                        of exotic spices and botanicals, offering a tantalizing symphony of flavors with every sip.
                        Whether enjoyed beneath the African sky or as a refreshing indulgence, Morula Surprise promises
                        a delightful journey, revealing the magic of Botswana''s cultural heritage in each enchanting
                        bottle.', 'assets/images/drink-1.png', 319.95);

insert into products (name, category, description, url, price) values ('Morula Strawberry Surprise', 'Alcoholic', 'Introducing "Morula Strawberry Surprise" – an enchanting fusion of Botswana''s revered Morula fruit and the luscious sweetness of ripe strawberries. Crafted with meticulous care and expertise by Ibrew, this tantalizing alcoholic beverage marries the rich, exotic flavors of Morula with the vibrant tang of succulent strawberries, creating a symphony of taste sensations that dance across the palate. With each sip, indulge in the delightful surprise of harmonious flavors, as the sweetness of strawberries intertwines seamlessly with the smooth, tropical notes of Morula, leaving a lingering sensation of pure bliss. Whether enjoyed on a balmy evening under the African sky or shared among friends, Morula Strawberry Surprise promises an unforgettable drinking experience, transporting you to a world of exotic delights with every sip.', 'assets/images/drink-2.png', 228.95);

insert into products (name, category, description, url, price) values ('Morula Juice', 'Non-Alcoholic', 'Introducing "Morula Juice" – a refreshing non-alcoholic elixir that celebrates the essence of Botswana''s beloved Morula fruit. Crafted with care by Ibrew, this invigorating beverage offers a pure and unadulterated taste of the African savannah. From the moment it touches your lips, Morula Juice delights the palate with the rich, tropical flavors of handpicked Morula fruits, each sip reminiscent of the sun-drenched landscapes where these fruits flourish. Embark on a sensory journey as the natural sweetness of Morula envelops your senses, leaving you feeling revitalized and nourished. Perfect for any occasion, Morula Juice is a testament to Botswana''s rich cultural heritage and the timeless allure of its native fruits.', 'assets/images/drink-3.png', 58.95);

insert into products (name, category, description, url, price) values ('Morula Galaxy', 'Alcoholic', '
Introducing "Morula Galaxy" – an ethereal alcoholic concoction that transports you on a celestial journey through the depths of flavor. Crafted with finesse by Ibrew, Morula Galaxy combines the exotic essence of Botswana''s Morula fruit with a cosmic burst of celestial flavors. With each sip, embark on a voyage through the stars as the velvety smoothness of Morula intertwines with celestial hints of mystery and intrigue. Enveloped in a galaxy of taste sensations, you''ll discover layers of complexity that unfold like constellations in the night sky. Whether enjoyed under the stars or as a toast to the wonders of the universe, Morula Galaxy promises an otherworldly drinking experience that''s truly out of this world.', 'assets/images/drink-4.png', 278.95);

insert into products (name, category, description, url, price) values ('Morula Sunset Can', 'Non-Alcoholic', 'Introducing "Morula Sunset Can" – a captivating non-alcoholic beverage that encapsulates the serene beauty of Botswana''s twilight skies. Crafted with passion by Ibrew, this refreshing elixir offers a taste of the African horizon with every sip. As the sun dips below the savannah, Morula Sunset Can captures the warm hues of the setting sun, infusing the essence of Morula fruit with a gentle sweetness that lingers on the palate. With each refreshing sip, indulge in the tranquil harmony of flavors, reminiscent of a peaceful evening beneath the African sky. Perfect for unwinding after a long day or simply savoring a moment of tranquility, Morula Sunset Can is a testament to the natural splendor and timeless allure of Botswana''s landscapes.', 'assets/images/drink-5.png', 69.95);

insert into products (name, category, description, url, price) values ('Morula Original', 'Alcoholic', 'Introducing "Morula Original" – a timeless alcoholic elixir that pays homage to the rich heritage of Botswana''s Morula fruit. Crafted with reverence by Ibrew, Morula Original embodies the essence of tradition and authenticity in every drop. From the first sip, experience the pure essence of handpicked Morula fruits, carefully distilled to perfection to capture the true spirit of the African savannah. With its smooth and robust flavor profile, Morula Original is a celebration of Botswana''s cultural legacy, offering a taste of history with each indulgent sip. Whether savored on its own or enjoyed in the company of friends, Morula Original is a testament to the enduring allure and timeless appeal of Botswana''s native fruits.', 'assets/images/drink-6.png', 128.95);